const languages = {
    'ko': {
        'site_title': '노아인테리어 - 목공 & 목조주택 전문',
        'logo_text': '노아인테리어',
        'nav_language': '언어',
        'nav_contact': '연락처',
        'home_title': '노아인테리어',
        'home_subtitle': '전주 및 전라북도 무료 출장 상담',
        'business_title': '주요 사업',
        'oem_title': '내장 목공 인테리어',
        'oem_desc': '아파트, 주택, 상업 공간 등 고객 맞춤형 내장 목공 인테리어를 전문으로 시공합니다.',
        'brand_title': '목조 주택',
        'brand_desc': '천연 목재 및 친환경 재료를 사용하여 건강하고 아름다운 목조 주택을 짓습니다.',
        'products_title': '주요 서비스',
        'products_desc': '노아인테리어의 전문적인 시공 서비스를 만나보세요.',
        'product1_title': '목조주택',
        'product1_desc': '자연과 함께하는 튼튼하고 아름다운 집',
        'product2_title': '상업공간',
        'product2_desc': '매장의 가치를 높이는 감각적인 인테리어',
        'product3_title': '주거공간',
        'product3_desc': '삶의 질을 높이는 편안한 인테리어',
        'product4_title': '맞춤가구',
        'product4_desc': '공간에 딱 맞는 나만의 가구 제작',
        'location_title': '사업장 위치',
        'location_desc': '노아인테리어는 전라북도 전주시에 위치하고 있습니다.',
        'address_label': '주소:',
        'contact_title': '연락처',
        'contact_desc': '궁금한 점이 있으시면 언제든지 문의해 주세요.',
        'rep_label': '대표:',
        'phone_label': '연락처:',
        'email_label': '이메일:',
        'quote_title': '견적 요청',
        'quote_desc': '아래 양식을 작성해주시면 담당자가 확인 후 신속하게 연락드리겠습니다.',
        'footer_text': '© 2025 노아인테리어. All Rights Reserved.'
    },
    'en': {
        'site_title': 'NOAH INTERIOR - Woodworking & Wooden House Specialist',
        'logo_text': 'NOAH Int',
        'nav_language': 'Language',
        'nav_contact': 'Contact',
        'home_title': 'NOAH INTERIOR',
        'home_subtitle': 'Free On-site Consultation in Jeonju & Jeollabuk-do',
        'business_title': 'Main Business',
        'oem_title': 'Interior Woodwork',
        'oem_desc': 'We specialize in custom interior woodworking for apartments, houses, and commercial spaces.',
        'brand_title': 'Wooden Houses',
        'brand_desc': 'We build healthy and beautiful wooden houses using natural wood and eco-friendly materials.',
        'products_title': 'Main Services',
        'products_desc': 'Explore NOAH INTERIOR\'s professional construction services.',
        'product1_title': 'Wooden Houses',
        'product1_desc': 'Strong and beautiful homes in harmony with nature',
        'product2_title': 'Commercial Spaces',
        'product2_desc': 'Sensible interiors that enhance store value',
        'product3_title': 'Residential Spaces',
        'product3_desc': 'Comfortable interiors that improve quality of life',
        'product4_title': 'Custom Furniture',
        'product4_desc': 'Creating your own furniture that fits your space perfectly',
        'location_title': 'Location',
        'location_desc': 'NOAH INTERIOR is located in Jeonju, Jeollabuk-do.',
        'address_label': 'Address:',
        'contact_title': 'Contact',
        'contact_desc': 'Please feel free to contact us if you have any questions.',
        'rep_label': 'Representative:',
        'phone_label': 'Contact:',
        'email_label': 'Email:',
        'quote_title': 'Request a Quote',
        'quote_desc': 'Please fill out the form below, and our representative will contact you shortly.',
        'footer_text': '© 2025 NOAH INTERIOR. All Rights Reserved.'
    },
    'vi': {
        'site_title': 'NOAH INTERIOR - Chuyên gia về Mộc & Nhà gỗ',
        'logo_text': 'NOAH Int',
        'nav_language': 'Ngôn ngữ',
        'nav_contact': 'Liên hệ',
        'home_title': 'NOAH INTERIOR',
        'home_subtitle': 'Tư vấn tận nơi miễn phí tại Jeonju & Jeollabuk-do',
        'business_title': 'Kinh doanh chính',
        'oem_title': 'Thi công nội thất gỗ',
        'oem_desc': 'Chúng tôi chuyên thi công nội thất gỗ tùy chỉnh cho căn hộ, nhà ở và không gian thương mại.',
        'brand_title': 'Nhà gỗ',
        'brand_desc': 'Chúng tôi xây dựng những ngôi nhà gỗ khỏe mạnh và xinh đẹp bằng gỗ tự nhiên và vật liệu thân thiện với môi trường.',
        'products_title': 'Dịch vụ chính',
        'products_desc': 'Khám phá các dịch vụ thi công chuyên nghiệp của NOAH INTERIOR.',
        'product1_title': 'Nhà gỗ',
        'product1_desc': 'Những ngôi nhà vững chắc và xinh đẹp hòa hợp với thiên nhiên',
        'product2_title': 'Không gian thương mại',
        'product2_desc': 'Nội thất tinh tế nâng cao giá trị cửa hàng',
        'product3_title': 'Không gian dân cư',
        'product3_desc': 'Nội thất tiện nghi nâng cao chất lượng cuộc sống',
        'product4_title': 'Nội thất tùy chỉnh',
        'product4_desc': 'Tạo ra đồ nội thất của riêng bạn phù hợp hoàn hảo với không gian của bạn',
        'location_title': 'Vị trí',
        'location_desc': 'NOAH INTERIOR đặt tại Jeonju, Jeollabuk-do.',
        'address_label': 'Địa chỉ:',
        'contact_title': 'Liên hệ',
        'contact_desc': 'Nếu bạn có bất kỳ câu hỏi nào, xin vui lòng liên hệ.',
        'rep_label': 'Đại diện:',
        'phone_label': 'Điện thoại:',
        'email_label': 'Email:',
        'quote_title': 'Yêu cầu báo giá',
        'quote_desc': 'Vui lòng điền vào biểu mẫu dưới đây, đại diện của chúng tôi sẽ sớm liên hệ với bạn.',
        'footer_text': '© 2025 NOAH INTERIOR. Mọi quyền được bảo lưu.'
    },
    'ja': {
        'site_title': 'NOAH INTERIOR - 木工＆木造住宅専門',
        'logo_text': 'NOAH Int',
        'nav_language': '言語',
        'nav_contact': '問合せ',
        'home_title': 'NOAH INTERIOR',
        'home_subtitle': '全州および全羅北道 無料出張相談',
        'business_title': '主な事業',
        'oem_title': '内装木工事',
        'oem_desc': 'アパート、住宅、商業施設など、オーダーメイドの内装木工事を専門としています。',
        'brand_title': '木造住宅',
        'brand_desc': '天然木と環境に優しい素材を使用し、健康的で美しい木造住宅を建てます。',
        'products_title': '主なサービス',
        'products_desc': 'NOAH INTERIORの専門的な施工サービスをご覧ください。',
        'product1_title': '木造住宅',
        'product1_desc': '自然と調和した、丈夫で美しい家',
        'product2_title': '商業空間',
        'product2_desc': '店舗の価値を高める洗練されたインテリア',
        'product3_title': '住居空間',
        'product3_desc': '生活の質を高める快適なインテリア',
        'product4_title': 'オーダーメイド家具',
        'product4_desc': '空間にぴったりの自分だけの家具作り',
        'location_title': '事業所の場所',
        'location_desc': 'NOAH INTERIORは全羅北道全州市にあります。',
        'address_label': '住所:',
        'contact_title': 'お問い合わせ',
        'contact_desc': 'ご不明な点がございましたら、お気軽にお問い合わせください。',
        'rep_label': '代表:',
        'phone_label': '連絡先:',
        'email_label': 'メール:',
        'quote_title': '見積もり依頼',
        'quote_desc': '下記のフォームにご記入ください。担当者より折り返しご連絡いたします。',
        'footer_text': '© 2025 NOAH INTERIOR. All Rights Reserved.'
    }
};
